# Automatically generated by pb2py
# fmt: off
# isort:skip_file
import protobuf as p

from .SymbolAccountMetadata import SymbolAccountMetadata

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SymbolMosaicNamespaceMetadata(p.MessageType):

    def __init__(
        self,
        *,
        header: Optional[SymbolAccountMetadata] = None,
        target_id: Optional[int] = None,
    ) -> None:
        self.header = header
        self.target_id = target_id

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('header', SymbolAccountMetadata, None),
            2: ('target_id', p.UVarintType, None),
        }
