# Automatically generated by pb2py
# fmt: off
# isort:skip_file
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SymbolMosaicGlobalRestriction(p.MessageType):

    def __init__(
        self,
        *,
        mosaic_id: Optional[int] = None,
        reference_mosaic_id: Optional[int] = None,
        restriction_key: Optional[int] = None,
        previous_restriction_value: Optional[int] = None,
        new_restriction_value: Optional[int] = None,
        previous_restriction_type: Optional[int] = None,
        new_restriction_type: Optional[int] = None,
    ) -> None:
        self.mosaic_id = mosaic_id
        self.reference_mosaic_id = reference_mosaic_id
        self.restriction_key = restriction_key
        self.previous_restriction_value = previous_restriction_value
        self.new_restriction_value = new_restriction_value
        self.previous_restriction_type = previous_restriction_type
        self.new_restriction_type = new_restriction_type

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('mosaic_id', p.UVarintType, None),
            2: ('reference_mosaic_id', p.UVarintType, None),
            3: ('restriction_key', p.UVarintType, None),
            4: ('previous_restriction_value', p.UVarintType, None),
            5: ('new_restriction_value', p.UVarintType, None),
            6: ('previous_restriction_type', p.UVarintType, None),
            7: ('new_restriction_type', p.UVarintType, None),
        }
