# Automatically generated by pb2py
# fmt: off
# isort:skip_file
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

ACCOUNT_KEY_LINK: Literal[16716] = 16716
NODE_KEY_LINK: Literal[16972] = 16972
VRF_KEY_LINK: Literal[16963] = 16963
VOTING_KEY_LINK: Literal[16707] = 16707
TRANSFER: Literal[16724] = 16724
MOSAIC_DEFINITION: Literal[16717] = 16717
MOSAIC_SUPPLY_CHANGE: Literal[16973] = 16973
NAMESPACE_REGISTRATION: Literal[16718] = 16718
ADDRESS_ALIAS: Literal[16974] = 16974
