# Automatically generated by pb2py
# fmt: off
# isort:skip_file
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

MAIN_NET: Literal[104] = 104
TEST_NET: Literal[152] = 152
PRIVATE: Literal[96] = 96
PRIVATE_TEST: Literal[144] = 144
