# Automatically generated by pb2py
# fmt: off
# isort:skip_file
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SymbolMultisigAccountModification(p.MessageType):

    def __init__(
        self,
        *,
        address_additions: Optional[List[str]] = None,
        address_deletions: Optional[List[str]] = None,
        min_removal_delta: Optional[int] = None,
        min_approval_delta: Optional[int] = None,
        reserve: Optional[int] = None,
    ) -> None:
        self.address_additions = address_additions if address_additions is not None else []
        self.address_deletions = address_deletions if address_deletions is not None else []
        self.min_removal_delta = min_removal_delta
        self.min_approval_delta = min_approval_delta
        self.reserve = reserve

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('min_removal_delta', p.UVarintType, None),
            2: ('min_approval_delta', p.UVarintType, None),
            3: ('reserve', p.UVarintType, None),
            4: ('address_additions', p.UnicodeType, p.FLAG_REPEATED),
            5: ('address_deletions', p.UnicodeType, p.FLAG_REPEATED),
        }
