# Automatically generated by pb2py
# fmt: off
# isort:skip_file
from .. import protobuf as p

from .SymbolAddressAlias import SymbolAddressAlias
from .SymbolKeyLink import SymbolKeyLink
from .SymbolMosaicDefinition import SymbolMosaicDefinition
from .SymbolMosaicSupplyChange import SymbolMosaicSupplyChange
from .SymbolNamespaceRegistration import SymbolNamespaceRegistration
from .SymbolTransactionCommon import SymbolTransactionCommon
from .SymbolTransfer import SymbolTransfer
from .SymbolVotingKeyLink import SymbolVotingKeyLink

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SymbolSignTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 90

    def __init__(
        self,
        *,
        transaction: Optional[SymbolTransactionCommon] = None,
        transfer: Optional[SymbolTransfer] = None,
        account_key_link: Optional[SymbolKeyLink] = None,
        node_key_link: Optional[SymbolKeyLink] = None,
        vrf_key_link: Optional[SymbolKeyLink] = None,
        voting_key_link: Optional[SymbolVotingKeyLink] = None,
        mosaic_definition: Optional[SymbolMosaicDefinition] = None,
        mosaic_supply_change: Optional[SymbolMosaicSupplyChange] = None,
        namespace_registration: Optional[SymbolNamespaceRegistration] = None,
        address_alias: Optional[SymbolAddressAlias] = None,
    ) -> None:
        self.transaction = transaction
        self.transfer = transfer
        self.account_key_link = account_key_link
        self.node_key_link = node_key_link
        self.vrf_key_link = vrf_key_link
        self.voting_key_link = voting_key_link
        self.mosaic_definition = mosaic_definition
        self.mosaic_supply_change = mosaic_supply_change
        self.namespace_registration = namespace_registration
        self.address_alias = address_alias

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('transaction', SymbolTransactionCommon, None),
            2: ('transfer', SymbolTransfer, None),
            3: ('account_key_link', SymbolKeyLink, None),
            4: ('node_key_link', SymbolKeyLink, None),
            5: ('vrf_key_link', SymbolKeyLink, None),
            6: ('voting_key_link', SymbolVotingKeyLink, None),
            7: ('mosaic_definition', SymbolMosaicDefinition, None),
            8: ('mosaic_supply_change', SymbolMosaicSupplyChange, None),
            9: ('namespace_registration', SymbolNamespaceRegistration, None),
            10: ('address_alias', SymbolAddressAlias, None),
        }
