# Automatically generated by pb2py
# fmt: off
# isort:skip_file
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SymbolMosaicDefinition(p.MessageType):

    def __init__(
        self,
        *,
        id: Optional[int] = None,
        duration: Optional[int] = None,
        nonce: Optional[int] = None,
        flags: Optional[int] = None,
        divisibility: Optional[int] = None,
    ) -> None:
        self.id = id
        self.duration = duration
        self.nonce = nonce
        self.flags = flags
        self.divisibility = divisibility

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('id', p.UVarintType, None),
            2: ('duration', p.UVarintType, None),
            3: ('nonce', p.UVarintType, None),
            4: ('flags', p.UVarintType, None),
            5: ('divisibility', p.UVarintType, None),
        }
