# Automatically generated by pb2py
# fmt: off
# isort:skip_file
from .. import protobuf as p

from .SymbolTransactionCommon import SymbolTransactionCommon
from .SymbolTransfer import SymbolTransfer

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SymbolSignTx(p.MessageType):

    def __init__(
        self,
        *,
        common: Optional[SymbolTransactionCommon] = None,
        transfer: Optional[SymbolTransfer] = None,
    ) -> None:
        self.common = common
        self.transfer = transfer

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('common', SymbolTransactionCommon, None),
            2: ('transfer', SymbolTransfer, None),
        }
