# Automatically generated by pb2py
# fmt: off
# isort:skip_file
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SymbolAccountMetadata(p.MessageType):

    def __init__(
        self,
        *,
        address: Optional[str] = None,
        scoped_metadata_key: Optional[int] = None,
        value_size_delta: Optional[int] = None,
        value: Optional[bytes] = None,
    ) -> None:
        self.address = address
        self.scoped_metadata_key = scoped_metadata_key
        self.value_size_delta = value_size_delta
        self.value = value

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('address', p.UnicodeType, None),
            2: ('scoped_metadata_key', p.UVarintType, None),
            3: ('value_size_delta', p.UVarintType, None),
            4: ('value', p.BytesType, None),
        }
