# Automatically generated by pb2py
# fmt: off
# isort:skip_file
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SymbolNamespaceRegistration(p.MessageType):

    def __init__(
        self,
        *,
        duration: Optional[int] = None,
        parent_id: Optional[int] = None,
        id: Optional[int] = None,
        registration_type: Optional[int] = None,
        name: Optional[str] = None,
    ) -> None:
        self.duration = duration
        self.parent_id = parent_id
        self.id = id
        self.registration_type = registration_type
        self.name = name

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('duration', p.UVarintType, None),
            2: ('parent_id', p.UVarintType, None),
            3: ('id', p.UVarintType, None),
            4: ('registration_type', p.UVarintType, None),
            5: ('name', p.UnicodeType, None),
        }
