# Automatically generated by pb2py
# fmt: off
# isort:skip_file
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SymbolSecretProof(p.MessageType):

    def __init__(
        self,
        *,
        recipient: Optional[str] = None,
        secret: Optional[str] = None,
        hash_algorithm: Optional[int] = None,
        proof: Optional[str] = None,
    ) -> None:
        self.recipient = recipient
        self.secret = secret
        self.hash_algorithm = hash_algorithm
        self.proof = proof

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('recipient', p.UnicodeType, None),
            2: ('secret', p.UnicodeType, None),
            3: ('hash_algorithm', p.UVarintType, None),
            4: ('proof', p.UnicodeType, None),
        }
