# Automatically generated by pb2py
# fmt: off
# isort:skip_file
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SymbolAddressAlias(p.MessageType):

    def __init__(
        self,
        *,
        namespace_id: Optional[int] = None,
        address: Optional[str] = None,
        action: Optional[int] = None,
    ) -> None:
        self.namespace_id = namespace_id
        self.address = address
        self.action = action

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('namespace_id', p.UVarintType, None),
            2: ('address', p.UnicodeType, None),
            3: ('action', p.UVarintType, None),
        }
