#!/bin/sh
RETURN=0

# dump all coins except the first 3 (Bitcoin, Testnet, Regtest)
ALTCOINS=$(./common/tools/cointool.py dump -l -p -t | grep '"name"' | cut -d '"' -f 4 | tail -n +4)
# split on newlines only
OLDIFS=$IFS
IFS="
"
for altcoin in $ALTCOINS; do
    # echo :"$altcoin":
    if strings "$1" | grep "$altcoin" | grep -v TEXT_MARGIN_LEFT | grep -v _MIN_MNEMONIC_LENGTH_WORD ; then
        RETURN=1
    fi
done
IFS=$OLDIFS

exit $RETURN
